
Ext.define( 'NetFix.MovieData' ,
{	statics :
	{	data :
		[	{ 	title : 'Star Wars IV : A New Hope' ,
				averageRating : 4.4 ,
				length : 127 * 60 ,
				director : 'George Lucas' ,
				language : [ 'English' , 'Spanish (Neutral)' , 'French' ] ,
				subtitles : [ 'English' ] ,
				thisMovieIs : [ 'Imaginative' ] ,
				genres : [ 'Sci-Fi & Fantasy', 'Action Sci-Fi & Fantasy', 'Sci-Fi Adventure' ]
			 } ,
			{ 	title : 'Star Wars V: The Empire Strikes Back' ,
				averageRating : 4.4 ,
				length : 129 * 60 ,
				director : 'George Lucas' ,
				language : [ 'English' , 'Spanish (Neutral)' , 'French' ] ,
				subtitles : [ 'English' ] ,
				thisMovieIs : [ 'Dark', 'Exciting' , 'Imaginative' ] ,
				genres : [ 	'Children & Family Movies' , 'Sci-Fi & Fantasy',
								'Movies for ages 8 to 10', 'Movies for ages 11 to 12' ,
								'Action Sci-Fi & Fantasy' , 'Sci-Fi Adventure' , 'Family Sci-Fi & Fantasy' ]
			} ,
			{ 	title : 'Fantasia' ,
				averageRating : 3.9 ,
				length : 120 * 60 ,
				director : 'Walt Disney' ,
				language : [ 'English' ] ,
				subtitles : [ 'English' , 'Spanish (Neutral)' , 'French' ] ,
				thisMovieIs : [ 'Imaginative' ] ,
				genres : [	'Children & Family Movies' , 'Classic Movies' , 'Sci-Fi & Fantasy' ,
								'Movies for ages 5 to 7' , 'Movies for ages 8 to 10' , 'Movies for ages 11 to 12' ,
								'Family Features' , 'Classic Sci-Fi & Fantasy' , 'Fantasy' , 'Family Feature Animation' ,
								'Classic Children & Family Movies' , 'Family Sci-Fi & Fantasy' ]
			} ,
			{ 	title : 'Ghandi' ,
				averageRating : 3.9 ,
				length : 190 * 60 ,
				director : 'Richard Attenborough' ,
				language : [ 'English' , 'French' , 'Spanish' , 'Portuguese' ] ,
				subtitles : [ 'English' , 'Korean' , 'Spanish (Neutral)' , 'Portuguese' , 'French' ] ,
				thisMovieIs : [ 'Inspiring' ] ,
				genres : [	'Dramas', 'Biographical Dramas', 'Dramas based on real life', 'Political Dramas' ,
								'Social Issue Dramas' , 'British Movies' , '20th Century Period Pieces' , 'British Dramas' ]
			} ,
			{ 	title : 'Romeo and Juliet' ,
				averageRating : 3.7 ,
				length : 138 * 60 ,
				director : 'Franco Zeferelli' ,
				language : [ 'English' ] ,
				subtitles : [ 'English' ] ,
				thisMovieIs : [ 'Emotional' , 'Romantic' ] ,
				genres : [	'Classic Movies' , 'Dramas' , 'Romantic Movies' , 'Classic Dramas' , 'Romantic Dramas' ,
								'Tearjerkers' , 'British Movies' , 'Classic Romantic Movies' , 'British Dramas' ]
			} ,
			{ 	title : 'Indochine' ,
				averageRating : 3.7 ,
				length : 156 * 60 ,
				director : 'Régis Wargnier' ,
				language : [ 'French' ] ,
				subtitles : [ 'English' , 'Spanish (Neutral)' , 'French' ] ,
				thisMovieIs : [ 'Sentimental' , 'Romantic' ] ,
				genres : [ 'Dramas' , 'Foreign Movies' , 'Romantic Movies' , 'Foreign Dramas' ,
				'Romantic Dramas' , 'Romantic Foreign Movies', 'French Movies', 'French Dramas' ]
			} ,
			{ 	title : 'The Red Violin' ,
				averageRating : 3.9 ,
				length : 130 * 60 ,
				director : 'Francois Girard' ,
				language : [ 'English' ] ,
				subtitles : [ 'English' , 'Spanish (Neutral)' ] ,
				thisMovieIs : [ 'Cerebral' , 'Dark' , 'Romantic' ] ,
				genres : [	'Dramas' , 'Independent Movies' , 'Romantic Movies' , 'Thrillers' , 'Independent Dramas' ,
								'Period Pieces' , 'Romantic Dramas' , 'Romantic Independent Movies' ,
								'Independent Thrillers' , 'Mysteries' ]
			} ,
			{ 	title : 'Downfall (Der Untergang)' ,
				averageRating : 4 ,
				length : 156 * 60 ,
				director : 'Oliver Hirschbiegel' ,
				language : [ 'German' ] ,
				subtitles : [ 'English' ] ,
				thisMovieIs : [ 'Cerebral' , 'Dark' , 'Violent' ] ,
				genres : [	'Dramas' , 'Dramas based on real life', 'German Movies' ]
			}
		]
	}
}
)
